dbt_igaming_market_share:
  outputs:
    dev:
      catalog: workspace
      host: dbc-e082afff-fd1d.cloud.databricks.com
      http_path: /sql/1.0/warehouses/dc1ad4022d13590b
      schema: bronze
      threads: 2
      token: dapi6ae000a660d6e5398ef2db16060d7d8b
      type: databricks
    ci:
      type: databricks
      catalog: main
      # Isolate CI data by using the unique GitHub Run ID to avoid collision
      schema: "ci_pr_{{ env_var('GITHUB_RUN_ID') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
    prod:
      catalog: workspace
      host: dbc-e082afff-fd1d.cloud.databricks.com
      http_path: /sql/1.0/warehouses/dc1ad4022d13590b
      schema: bronze
      threads: 2
      token: dapi6ae000a660d6e5398ef2db16060d7d8b
      type: databricks
  target: dev